sudo: false

language: android
jdk: oraclejdk7

env:
  global:
    - ADB_INSTALL_TIMEOUT=10

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-24
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-17

before_install:
  - chmod +x gradlew
