sudo: false

language: android
jdk: oraclejdk7

env:
  global:
    - ADB_INSTALL_TIMEOUT=10

android:
  components:

    - tools

    - build-tools-23.0.2
    - android-24
    # support lib
    - extra-android-m2repository
    - extra-android-support

script:
  - gradlew clean assembleRelease

before_install:
  - chmod +x gradlew
